# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.6
    hooks:
      - id: terraform_fmt
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: master
    hooks:
      - id: docker-compose-check
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        entry: bash -c "cd server && black src --check"
