version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=000000000
      - AWS_SECRET_ACCESS_KEY=000000000
    ports:
      - "8000:8000"
    networks:
      - localstack_network
    volumes:
      - ./src/app:/app

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=lambda,sqs,s3,dynamodb
      - DEBUG=0
      - PERSISTENCE=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOG_LEVEL=debug
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "./data/local/:/state"
    networks:
      - localstack_network
    command: >
      sh -c '
        /usr/bin/localstack start;
      '

networks:
  localstack_network:
    driver: bridge
